apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-primos
spec:
  replicas: 3 # Número de workers en la búsqueda
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        # IMAGEN DE DOCKER HUB
        image: jukhg/primos-distribuidos:v1
        # Sobreescribimos el comando para que corra el script del worker
        command: ["python", "-u", "app/worker.py"] 
        env:
        - name: REDIS_HOST
          value: "redis-service"
        - name: MONGO_HOST
          value: "mongo-service"
